name: Markdownlint

on:
  pull_request:

jobs:
  mdl:
    runs-on: [self-hosted, jammy, edge]
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main
